name: SwiftFormat
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  SwiftFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Format
        uses: mtgto/swift-format-action@main
        with:
          configuration_file: .swift-format
          all_files: false
          max_warnings: -1
