name: SwiftLint
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
